trigger:
- master
- dev

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  - group: 'DockerHub'
  - name: 'imageName' 
    value: '$(Build.Repository.Name):$(Build.SourceBranchName)'

steps:
- script: echo "##vso[task.setvariable variable=imageNameNew]$(echo "$(imageName)" | sed -e 's/master/latest/g' | awk '{print tolower($0)}')"
  displayName: 'set variables'

- script: docker login -u $(user) -p $(password)
  displayName: 'docker login'

- script: docker build -f Dockerfile -t $(imageNameNew) .
  displayName: 'docker build'

- script: docker push $(imageNameNew)
  displayName: 'docker push'